# Generated by Django 4.1.3 on 2022-11-26 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('img_path', models.CharField(max_length=200)),
                ('head', models.CharField(max_length=200)),
                ('detail', models.TextField()),
            ],
        ),
    ]
