# Generated by Django 4.1.3 on 2022-11-28 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instsite', '0005_hashes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=16)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('img_path', models.CharField(max_length=200)),
                ('head', models.CharField(max_length=200)),
                ('detail', models.TextField()),
            ],
        ),
    ]
