# Generated by Django 4.1.3 on 2022-11-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instsite', '0006_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
