# Generated by Django 4.1.3 on 2022-11-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instsite', '0008_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hashes',
        ),
    ]
