# Generated by Django 4.1.3 on 2022-11-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instsite', '0009_delete_hashes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100)),
            ],
        ),
    ]
